{
 "title": "Spanner Active Queries Summary",
 "tags": [
  "active-queries-summary",
  "${PRODUCT_REPLACE}",
  "${ENVIRONMENT_REPLACE}",
  "${PROJECT_REPLACE}",
  "${PRODUCT_REPLACE}-${ENVIRONMENT_REPLACE}"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "project", "label": "Project", "query": { "query": "label_values(project_id)" } },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance_id)" } },
   { "name": "database", "label": "Database", "query": { "query": "label_values(database)" } }
  ]
 },
 "panels": [
  {
   "title": "Active count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (database) (database_spanner_active_queries_summary_active_count{database=~\"$${database}\",instance_id=~\"$${instance}\",project_id=~\"$${project}\"})",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Older than 1 second count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (database) (database_spanner_active_queries_summary_count_older_than_1s{database=~\"$${database}\",instance_id=~\"$${instance}\",project_id=~\"$${project}\"})",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Older than 10 seconds count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (database) (database_spanner_active_queries_summary_count_older_than_10s{database=~\"$${database}\",instance_id=~\"$${instance}\",project_id=~\"$${project}\"})",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Older than 100 seconds count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (database) (database_spanner_active_queries_summary_count_older_than_100s{database=~\"$${database}\",instance_id=~\"$${instance}\",project_id=~\"$${project}\"})",
     "legendFormat": "{{database}}"
    }
   ]
  }
 ]
}