{
 "title": "Spanner Database dashboard",
 "description": "Cloud Monitoring | Database dashboard",
 "tags": [
  "cloud-monitoring-database",
  "cloud-monitoring-database-${PRODUCT_REPLACE}-${ENVIRONMENT_REPLACE}",
  "${PRODUCT_REPLACE}",
  "${ENVIRONMENT_REPLACE}",
  "${PROJECT_REPLACE}",
  "${PRODUCT_REPLACE}-${ENVIRONMENT_REPLACE}"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "gcmds", "label": "Cloud Monitoring", "query": "stackdriver" },
   { "name": "pds", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "project",
    "label": "Project",
    "query": {}
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {}
   },
   {
    "name": "database",
    "label": "Database",
    "query": {}
   },
   {
    "name": "latencyPercentile",
    "label": "Latency percentile",
    "query": "99th percentile : 99, 50th percentile : 50"
   }
  ]
 },
 "panels": [
  {
   "title": "Total CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{metric.label.database}}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "mql",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project",
      "query": "fetch spanner_instance\n| metric 'spanner.googleapis.com/instance/cpu/utilization'\n| filter\n    resource.instance_id == '$instance' && metric.database =~ '$database'\n| group_by 1m,\n    [value_utilization_mean: mean(value.utilization )]\n| every 1m\n| group_by [metric.database],\n    [value_utilization_mean_aggregate:\n       aggregate(value_utilization_mean)]\n",
      "valueType": ""
     },
     "sloQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "selectorName": "select_slo_health",
      "serviceId": "",
      "serviceName": "",
      "sloId": "",
      "sloName": ""
     }
    }
   ]
  },
  {
   "title": "Total lock wait",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "database_spanner_lock_stats_total_total_lock_wait_seconds{database=~\"$database\",instance_id=~\"$instance\",project_id=~\"$project\"}",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Write latency - $latencyPercentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{metric.label.database}}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "mql",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project",
      "query": "fetch spanner_instance\n| metric 'spanner.googleapis.com/api/request_latencies'\n| filter\n    resource.instance_id == '$instance'\n    &&\n    metric.method == 'Commit'\n    && metric.database =~ '$database'\n| group_by 1m,\n    [value_request_latencies_aggregate: aggregate(value.request_latencies)]\n| every 1m\n| group_by [metric.database],\n    [value_request_latencies_aggregate_percentile:\n       percentile(value_request_latencies_aggregate, $latencyPercentile)]\n",
      "valueType": ""
     },
     "sloQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "selectorName": "select_slo_health",
      "serviceId": "",
      "serviceName": "",
      "sloId": "",
      "sloName": ""
     }
    }
   ]
  },
  {
   "title": "Read latency - $latencyPercentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{metric.label.database}}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "mql",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project",
      "query": "fetch spanner_instance\n| metric 'spanner.googleapis.com/api/request_latencies'\n| filter\n    resource.instance_id == '$instance'\n    &&\n     metric.method\n     =~ 'ExecuteBatchDml|ExecuteSql|ExecuteStreamingSql|Read|StreamingRead'\n    && metric.database =~ '$database'\n| group_by 1m,\n    [value_request_latencies_aggregate: aggregate(value.request_latencies)]\n| every 1m\n| group_by [metric.database],\n    [value_request_latencies_aggregate_percentile:\n       percentile(value_request_latencies_aggregate, $latencyPercentile)]\n",
      "valueType": ""
     },
     "sloQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "selectorName": "select_slo_health",
      "serviceId": "",
      "serviceName": "",
      "sloId": "",
      "sloName": ""
     }
    }
   ]
  },
  {
   "title": "Write operations per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{metric.label.database}}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "mql",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project",
      "query": "fetch spanner_instance\n| metric 'spanner.googleapis.com/api/api_request_count'\n| filter\n    (resource.instance_id == '$instance')\n    &&\n    (metric.method == 'Commit')\n    && metric.database =~ '$database'\n| align rate(1m)\n| every 1m\n| group_by [metric.database],\n    [value_api_request_count_aggregate: aggregate(value.api_request_count)]\n",
      "valueType": ""
     },
     "sloQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "selectorName": "select_slo_health",
      "serviceId": "",
      "serviceName": "",
      "sloId": "",
      "sloName": ""
     }
    }
   ]
  },
  {
   "title": "Read operations per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{metric.label.database}}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "mql",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project",
      "query": "fetch spanner_instance\n| metric 'spanner.googleapis.com/api/api_request_count'\n| filter\n    (resource.instance_id == '$instance')\n    &&\n    (metric.method\n     =~ 'ExecuteBatchDml|ExecuteSql|ExecuteStreamingSql|Read|StreamingRead')\n    && metric.database =~ '$database'\n| align rate(1m)\n| every 1m\n| group_by [metric.database],\n    [value_api_request_count_aggregate: aggregate(value.api_request_count)]\n",
      "valueType": ""
     },
     "sloQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "selectorName": "select_slo_health",
      "serviceId": "",
      "serviceName": "",
      "sloId": "",
      "sloName": ""
     }
    }
   ]
  },
  {
   "title": "Write throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{metric.label.database}}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "mql",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project",
      "query": "fetch spanner_instance\n| metric 'spanner.googleapis.com/api/received_bytes_count'\n| filter\n    (resource.instance_id == '$instance')\n    && (metric.method = 'Commit')\n    && metric.database =~ '$database'\n| align rate(1m)\n| every 1m\n| group_by [metric.database],\n    [value_received_bytes_count_aggregate: aggregate(value.received_bytes_count)]\n",
      "valueType": ""
     },
     "sloQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "selectorName": "select_slo_health",
      "serviceId": "",
      "serviceName": "",
      "sloId": "",
      "sloName": ""
     }
    }
   ]
  },
  {
   "title": "Read throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{metric.label.database}}",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "mql",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project",
      "query": "fetch spanner_instance\n| metric 'spanner.googleapis.com/api/sent_bytes_count'\n| filter\n    (resource.instance_id == '$instance')\n    && (metric.method =~ 'ExecuteBatchDml|ExecuteSql|ExecuteStreamingSql|Read|StreamingRead')\n    && metric.database =~ '$database'\n| align rate(1m)\n| every 1m\n| group_by [metric.database],\n    [value_sent_bytes_count_aggregate: aggregate(value.sent_bytes_count)]\n",
      "valueType": ""
     },
     "sloQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$project",
      "selectorName": "select_slo_health",
      "serviceId": "",
      "serviceName": "",
      "sloId": "",
      "sloName": ""
     }
    }
   ]
  }
 ]
}