{
 "title": "Read details",
 "tags": [ "read-details" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "pds", "label": "Prometheus", "query": "prometheus" },
   { "name": "project", "label": "Project", "query": { "query": "label_values(project_id)" } },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance_id)" } },
   { "name": "database", "label": "Database", "query": { "query": "label_values(database)" } },
   {
    "name": "read_columns_topn",
    "label": "Top 10 Read Columns",
    "query": {
     "query": "query_result(topk(10, avg_over_time(database_spanner_read_stats_top_avg_cpu_seconds[${__range_s}s])))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Average CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (project_id,instance_id,database,read_columns)(database_spanner_read_stats_top_avg_cpu_seconds{fingerprint=~\"$read_columns_topn\", database=~\"$database\", instance_id=~\"$instance\", project_id=~\"$project\"})",
     "legendFormat": "{{read_columns}}"
    }
   ]
  },
  {
   "title": "Execution count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (project_id,instance_id,database,read_columns)(database_spanner_read_stats_top_execution_count{fingerprint=~\"$read_columns_topn\", database=~\"$database\", instance_id=~\"$instance\", project_id=~\"$project\"})",
     "legendFormat": "{{read_columns}}"
    }
   ]
  },
  {
   "title": "Average Rows",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg by (project_id,instance_id,database,read_columns)(database_spanner_read_stats_top_avg_rows{fingerprint=~\"$read_columns_topn\", database=~\"$database\", instance_id=~\"$instance\", project_id=~\"$project\"})",
     "legendFormat": "{{read_columns}}"
    }
   ]
  },
  {
   "title": "Average Client Wait Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (project_id,instance_id,database,read_columns)(database_spanner_read_stats_top_avg_client_wait_seconds{fingerprint=~\"$read_columns_topn\", database=~\"$database\", instance_id=~\"$instance\", project_id=~\"$project\"})",
     "legendFormat": "{{read_columns}}"
    }
   ]
  },
  {
   "title": "Average Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (project_id,instance_id,database,read_columns)(database_spanner_read_stats_top_avg_bytes{fingerprint=~\"$read_columns_topn\", database=~\"$database\", instance_id=~\"$instance\", project_id=~\"$project\"})",
     "legendFormat": "{{read_columns}}"
    }
   ]
  },
  {
   "title": "Average Leader Refresh Delay Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (project_id,instance_id,database,read_columns)(database_spanner_read_stats_top_avg_leader_refresh_delay_seconds{fingerprint=~\"$read_columns_topn\", database=~\"$database\", instance_id=~\"$instance\", project_id=~\"$project\"})",
     "legendFormat": "{{read_columns}}"
    }
   ]
  },
  {
   "title": "Average Locking Delay Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (project_id,instance_id,database,read_columns)(database_spanner_read_stats_top_avg_locking_delay_seconds{fingerprint=~\"$read_columns_topn\", database=~\"$database\", instance_id=~\"$instance\", project_id=~\"$project\"})",
     "legendFormat": "{{read_columns}}"
    }
   ]
  },
  {
   "title": "Summary",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "database_spanner_read_stats_top_avg_cpu_seconds{fingerprint=~\"$read_columns_topn\", database=~\"$database\", instance_id=~\"$instance\", project_id=~\"$project\"}"
    },
    {
     "expr": "database_spanner_read_stats_top_execution_count{fingerprint=~\"$read_columns_topn\", database=~\"$database\", instance_id=~\"$instance\", project_id=~\"$project\"}"
    }
   ]
  }
 ]
}